---
title: "csv_to_genepop_format"
author: "Tanya Lama"
date: "6/29/2021"
output: html_document
---
csv_to_genepop_format
```{r setup, include=FALSE}
#Inputs 
library(readr)
library(dplyr)
library(stringr)

#Raw fluidigm data should be in *.csv format (see github for example)

#Set working directory
setwd("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/github_iberian_lynx/")
#Import *.csv
data<-  read.csv("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/github_iberian_lynx/output_fluidigm_junio2021_setupsedited.csv")

#Rename the columns
names(data) <- as.character(c("id", "assay", "allele_x", "allele_y", "name", "type", "auto", "confidence", "final", "converted", "fluoresc_x", "fluoresc_y", "comments"))
data<- data[14:9232,] #drop the first 13 rows. A fluidigm plate produces 9232 rows of raw data. If you are doing anything OTHER than taking raw fluidigm data in csv format --> genepop format, you will need to review all row and column selections in this script

#add a column called "well" to the FRONT of data
data<- data.frame(well = c(1:9219), data)

#extract the first half of id (S**_A**) and assign to well
data$well<- (str_extract(string = data$id, pattern = "S[0-96]+"))

#import *.csv with the proper id names
names<- read.csv("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/R_iberian_lynx/input_names_csv_to_genepop_format.csv")

#for every well (S**) in data replace with well_id (S**_name) in names
#data["well"][data["well"] == "S96"] <- "S96_ntc" *** this works
data["well"][data["well"] =="S01"]<-"S01_pipa"
data["well"][data["well"] =="S02"]<-"S02_pulga"
data["well"][data["well"] =="S03"]<-"S03_ramada"
data["well"][data["well"] =="S04"]<-"S04_q1nairobi"
data["well"][data["well"] =="S05"]<-"S05_mel_2019"
data["well"][data["well"] =="S06"]<-"S06_qic27"
data["well"][data["well"] =="S07"]<-"S07_0044ri"
data["well"][data["well"] =="S08"]<-"S08_1141gang"
data["well"][data["well"] =="S09"]<-"S09_quintagono"
data["well"][data["well"] =="S10"]<-"S10_hyp_r1pedra"
data["well"][data["well"] =="S11"]<-"S11_m1_fresa"
data["well"][data["well"] =="S12"]<-"S12_hisopo_4"
data["well"][data["well"] =="S13"]<-"S13_pardal"
data["well"][data["well"] =="S14"]<-"S14_mundo"
data["well"][data["well"] =="S15"]<-"S15_paiciscaicus"
data["well"][data["well"] =="S16"]<-"S16_quantana"
data["well"][data["well"] =="S17"]<-"S17_mel_2020"
data["well"][data["well"] =="S18"]<-"S18_q_infante_tapete"
data["well"][data["well"] =="S19"]<-"S19_0189mo"
data["well"][data["well"] =="S20"]<-"S20_1141gang"
data["well"][data["well"] =="S21"]<-"S21_quintagono"
data["well"][data["well"] =="S22"]<-"S22_hyp_r1pedra"
data["well"][data["well"] =="S23"]<-"S23_m1_fresa"
data["well"][data["well"] =="S24"]<-"S24_hisopo_4"
data["well"][data["well"] =="S25"]<-"S25_pandora"
data["well"][data["well"] =="S26"]<-"S26_quiribo"
data["well"][data["well"] =="S27"]<-"S27_nossa"
data["well"][data["well"] =="S28"]<-"S28_qom"
data["well"][data["well"] =="S29"]<-"S29_quadrifolio"
data["well"][data["well"] =="S30"]<-"S30_q_gioes"
data["well"][data["well"] =="S31"]<-"S31_0371ri"
data["well"][data["well"] =="S32"]<-"S32_1141gang"
data["well"][data["well"] =="S33"]<-"S33_quintagono"
data["well"][data["well"] =="S34"]<-"S34_r1pedra"
data["well"][data["well"] =="S35"]<-"S35_m1_fresa"
data["well"][data["well"] =="S36"]<-"S36_hisopo_4"
data["well"][data["well"] =="S37"]<-"S37_parreira"
data["well"][data["well"] =="S38"]<-"S38_quinquilharia"
data["well"][data["well"] =="S39"]<-"S39_rodion"
data["well"][data["well"] =="S40"]<-"S40_r1lluvia"
data["well"][data["well"] =="S41"]<-"S41_nayem"
data["well"][data["well"] =="S42"]<-"S42_nairobi"
data["well"][data["well"] =="S43"]<-"S43_0047ri"
data["well"][data["well"] =="S44"]<-"S44_1141gang"
data["well"][data["well"] =="S45"]<-"S45_quintagono"
data["well"][data["well"] =="S46"]<-"S46_hyp_r1pedra"
data["well"][data["well"] =="S47"]<-"S47_m1_fresa"
data["well"][data["well"] =="S48"]<-"S48_hisopo_4"
data["well"][data["well"] =="S49"]<-"S49_nogado"
data["well"][data["well"] =="S50"]<-"S50_quip"
data["well"][data["well"] =="S51"]<-"S51_ramalina"
data["well"][data["well"] =="S52"]<-"S52_moreira"
data["well"][data["well"] =="S53"]<-"S53_oslo"
data["well"][data["well"] =="S54"]<-"S54_p2neves"
data["well"][data["well"] =="S55"]<-"S55_0576gang"
data["well"][data["well"] =="S56"]<-"S56_pelos"
data["well"][data["well"] =="S57"]<-"S57_picanco"
data["well"][data["well"] =="S58"]<-"S58_oriana"
data["well"][data["well"] =="S59"]<-"S59_hisopo_3"
data["well"][data["well"] =="S60"]<-"S60_c-ext_fore"
data["well"][data["well"] =="S61"]<-"S61_odeleite"
data["well"][data["well"] =="S62"]<-"S62_quadrado"
data["well"][data["well"] =="S63"]<-"S63_rombo"
data["well"][data["well"] =="S64"]<-"S64_feto_nao_nascido"
data["well"][data["well"] =="S65"]<-"S65_magreb"
data["well"][data["well"] =="S66"]<-"S66_portela"
data["well"][data["well"] =="S67"]<-"S67_0706gang"
data["well"][data["well"] =="S68"]<-"S68_pelos"
data["well"][data["well"] =="S69"]<-"S69_picanco"
data["well"][data["well"] =="S70"]<-"S70_oriana"
data["well"][data["well"] =="S71"]<-"S71_hisopo_3"
data["well"][data["well"] =="S72"]<-"S72_ntc"
data["well"][data["well"] =="S73"]<-"S73_portela"
data["well"][data["well"] =="S74"]<-"S74_quimica"
data["well"][data["well"] =="S75"]<-"S75_q1jacaranda"
data["well"][data["well"] =="S76"]<-"S76_quilica"
data["well"][data["well"] =="S77"]<-"S77_nabia"
data["well"][data["well"] =="S78"]<-"S78_nogado"
data["well"][data["well"] =="S79"]<-"S79_1738mo"
data["well"][data["well"] =="S80"]<-"S80_pelos"
data["well"][data["well"] =="S81"]<-"S81_picanco"
data["well"][data["well"] =="S82"]<-"S82_oriana"
data["well"][data["well"] =="S83"]<-"S83_hisopo_3"
data["well"][data["well"] =="S84"]<-"S84_ntc"
data["well"][data["well"] =="S85"]<-"S85_nairobi"
data["well"][data["well"] =="S86"]<-"S86_quilowat"
data["well"][data["well"] =="S87"]<-"S87_quimico"
data["well"][data["well"] =="S88"]<-"S88_neves"
data["well"][data["well"] =="S89"]<-"S89_oliveira"
data["well"][data["well"] =="S90"]<-"S90_lluvia"
data["well"][data["well"] =="S91"]<-"S91_2258ri"
data["well"][data["well"] =="S92"]<-"S92_pelos"
data["well"][data["well"] =="S93"]<-"S93_picanco"
data["well"][data["well"] =="S94"]<-"S94_oriana"
data["well"][data["well"] =="S95"]<-"S95_hisopo_3"
data["well"][data["well"] =="S96"]<-"S96_ntc"

#assign the assay name (lp***) to just the numbers following _
data$assay<- as.character(data$assay) #must convert to characters first
data["assay"][data["assay"] =="lp23.s00014_2590354"]<-"2590354" 
data["assay"][data["assay"] =="lp23.s10433_1503895"]<-"1503895"
data["assay"][data["assay"] =="lp23.s20851_716372"]<-"716372"
data["assay"][data["assay"] =="lp23.s26104_908637"]<-"908637"
data["assay"][data["assay"] =="lp23.s31305_1737806"]<-"1737806"
data["assay"][data["assay"] =="lp23.s36488_4052964"]<-"4052964"
data["assay"][data["assay"] =="lp23.s00009_1834017"]<-"1834017"
data["assay"][data["assay"] =="lp23.s05280_563540"]<-"563540"
data["assay"][data["assay"] =="lp23.s10443_914709"]<-"914709"
data["assay"][data["assay"] =="lp23.s15671_1506609"]<-"1506609"
data["assay"][data["assay"] =="lp23.s20863_1655874"]<-"1655874"
data["assay"][data["assay"] =="lp23.s26096_1566241"]<-"1566241"
data["assay"][data["assay"] =="lp23.s00052_725687"]<-"725687"
data["assay"][data["assay"] =="lp23.s36542_710478"]<-"710478"
data["assay"][data["assay"] =="lp23.s20853_3066457"]<-"3066457"
data["assay"][data["assay"] =="lp23.s26145_507929"]<-"507929"
data["assay"][data["assay"] =="lp23.s31310_1086363"]<-"1086363"
data["assay"][data["assay"] =="lp23.s36495_3581524"]<-"3581524"
data["assay"][data["assay"] =="lp23.s00009_2846018"]<-"2846018"
data["assay"][data["assay"] =="lp23.s05325_381840"]<-"381840"
data["assay"][data["assay"] =="lp23.s10479_740770"]<-"740770"
data["assay"][data["assay"] =="lp23.s15684_800122"]<-"800122"
data["assay"][data["assay"] =="lp23.s20902_801628"]<-"801628"
data["assay"][data["assay"] =="lp23.s26116_753836"]<-"753836"
data["assay"][data["assay"] =="lp23.s00058_679888"]<-"679888"
data["assay"][data["assay"] =="lp23.s10475_739665"]<-"739665"
data["assay"][data["assay"] =="lp23.s20876_620249"]<-"620249"
data["assay"][data["assay"] =="lp23.s26165_396817"]<-"396817"
data["assay"][data["assay"] =="lp23.s31330_644231"]<-"644231"
data["assay"][data["assay"] =="lp23.s36500_2547318"]<-"2547318"
data["assay"][data["assay"] =="SRY"]<-"SRY"
data["assay"][data["assay"] =="lp23.s05352_266388"]<-"266388"
data["assay"][data["assay"] =="lp23.s10493_588415"]<-"588415"
data["assay"][data["assay"] =="lp23.s15686_741104"]<-"741104"
data["assay"][data["assay"] =="lp23.s20939_475959"]<-"475959"
data["assay"][data["assay"] =="lp23.s31280_3770256"]<-"3770256"
data["assay"][data["assay"] =="lp23.s00067_625966"]<-"625966"
data["assay"][data["assay"] =="lp23.s36582_514659"]<-"514659"
data["assay"][data["assay"] =="lp23.s20903_744497"]<-"744497"
data["assay"][data["assay"] =="lp23.s26166_401956"]<-"401956"
data["assay"][data["assay"] =="lp23.s31340_650544"]<-"650544"
data["assay"][data["assay"] =="lp23.s36504_2474946"]<-"2474946"
data["assay"][data["assay"] =="lp23.s00047_782246"]<-"782246"
data["assay"][data["assay"] =="lp23.s10425_4620618"]<-"4620618"
data["assay"][data["assay"] =="lp23.s10539_327149"]<-"327149"
data["assay"][data["assay"] =="lp23.s15697_710275"]<-"710275"
data["assay"][data["assay"] =="lp23.s20944_474858"]<-"474858"
data["assay"][data["assay"] =="lp23.s31291_2271462"]<-"2271462"
data["assay"][data["assay"] =="lp23.s00098_542097"]<-"542097"
data["assay"][data["assay"] =="lp23.s10491_591326"]<-"591326"
data["assay"][data["assay"] =="lp23.s20935_527144"]<-"527144"
data["assay"][data["assay"] =="lp23.s26186_334126"]<-"334126"
data["assay"][data["assay"] =="lp23.s31363_463230"]<-"463230"
data["assay"][data["assay"] =="lp23.s36537_860433"]<-"860433"
data["assay"][data["assay"] =="lp23.s00070_672876"]<-"672876"
data["assay"][data["assay"] =="lp23.s10427_1619116"]<-"1619116"
data["assay"][data["assay"] =="lp23.s15643_2579704"]<-"2579704"
data["assay"][data["assay"] =="lp23.s15710_553408"]<-"553408"
data["assay"][data["assay"] =="lp23.s20972_323729"]<-"323729"
data["assay"][data["assay"] =="lp23.s31294_1494647"]<-"1494647"
data["assay"][data["assay"] =="lp23.s00157_236533"]<-"236533"
data["assay"][data["assay"] =="lp23.s10513_455860"]<-"455860"
data["assay"][data["assay"] =="lp23.s20965_236982"]<-"236982"
data["assay"][data["assay"] =="lp23.s31279_1702572"]<-"1702572"
data["assay"][data["assay"] =="lp23.s36585_430428"]<-"430428"
data["assay"][data["assay"] =="lp23.s36540_772318"]<-"772318"
data["assay"][data["assay"] =="lp23.s05220_2270749"]<-"2270749"
data["assay"][data["assay"] =="lp23.s10427_2643321"]<-"2643321"
data["assay"][data["assay"] =="lp23.s15645_528326"]<-"528326"
data["assay"][data["assay"] =="lp23.s20851_1728823"]<-"1728823"
data["assay"][data["assay"] =="lp23.s26064_4484957"]<-"4484957"
data["assay"][data["assay"] =="lp23.s31295_1901450"]<-"1901450"
data["assay"][data["assay"] =="lp23.s05240_638843"]<-"638843"
data["assay"][data["assay"] =="lp23.s15639_4974369"]<-"4974369"
data["assay"][data["assay"] =="lp23.s26069_2728733"]<-"2728733"
data["assay"][data["assay"] =="lp23.s31284_643543"]<-"643543"
data["assay"][data["assay"] =="lp23.s31410_305622"]<-"305622"
data["assay"][data["assay"] =="lp23.s31390_349301"]<-"349301"
data["assay"][data["assay"] =="ZFR"]<-"ZFR"
data["assay"][data["assay"] =="lp23.s10438_2602837"]<-"2602837"
data["assay"][data["assay"] =="lp23.s15647_2259949"]<-"2259949"
data["assay"][data["assay"] =="lp23.s20857_507888"]<-"507888"
data["assay"][data["assay"] =="lp23.s26068_1522554"]<-"1522554"
data["assay"][data["assay"] =="lp23.s31338_714163"]<-"714163"
data["assay"][data["assay"] =="lp23.s10425_7686152"]<-"7686152"
data["assay"][data["assay"] =="lp23.s15650_667736"]<-"667736"
data["assay"][data["assay"] =="lp23.s26088_771095"]<-"771095"
data["assay"][data["assay"] =="lp23.s31296_2122346"]<-"2122346"
data["assay"][data["assay"] =="lp23.s31411_285842"]<-"285842"
data["assay"][data["assay"] =="lp23.s31401_367222"]<-"367222"
data["assay"][data["assay"] =="lp23.s05265_752266"]<-"752266"
data["assay"][data["assay"] =="lp23.s10441_815319"]<-"815319"
data["assay"][data["assay"] =="lp23.s15667_1617558"]<-"1617558"
data["assay"][data["assay"] =="lp23.s20860_1920172"]<-"1920172"
data["assay"][data["assay"] =="lp23.s26086_796406"]<-"796406"
data["assay"][data["assay"] =="lp23.s31351_557254"]<-"557254"

#data$converted has the final genotype calls (e.g., C:G). We need to convert these to three-digit genepop format (Invalid = 000, No Call = 000, A=001, G=002, C=003, T=004)

#Insert a column after data$converted
data2<-data
data<- data.frame(data, final_x = c(1:9219))
data<- data.frame(data, final_y = c(1:9219))
data<- data.frame(data, genepop_x = c(1:9219))
data<- data.frame(data, genepop_y = c(1:9219))
data<- data.frame(data, genepop_xy = c(1:9219))

#change Invalid to Invalid:Invalid and No Call to NoCall:NoCall
data$converted<- as.character(data$converted) #must convert to characters first
data2["converted"][data2["converted"] =="Invalid" ]<-"Invalid:Invalid"
data2["converted"][data2["converted"] =="No Call" ]<-"NoCall:NoCall"

#Split data$converted and assign to columns final_x and final_y
library(stringr)
converted_split<- str_split_fixed(data2$converted, ":", 2)
converted_split<-as.data.frame(converted_split)
data2$final_x <- converted_split$V1
data2$final_y <- converted_split$V2

#Convert final_x and final_y into genepop three digit format in columns genepop_x and genepop_y
data2$final_x<- as.character(data2$final_x)
data2$final_y<- as.character(data2$final_y)
#copy values to genepop columns
data2$genepop_x<- as.character(data2$final_x)
data2$genepop_y<- as.character(data2$final_y)

####genepop_x
data2["genepop_x"][data2["genepop_x"] =="Invalid"]<-"000"
data2["genepop_x"][data2["genepop_x"] =="NoCall"]<-"000"
data2["genepop_x"][data2["genepop_x"] =="A"]<-"001"
data2["genepop_x"][data2["genepop_x"] =="G"]<-"002"
data2["genepop_x"][data2["genepop_x"] =="C"]<-"003"
data2["genepop_x"][data2["genepop_x"] =="T"]<-"004"

####genepop_y
data2["genepop_y"][data2["genepop_y"] =="Invalid"]<-"000"
data2["genepop_y"][data2["genepop_y"] =="NoCall"]<-"000"
data2["genepop_y"][data2["genepop_y"] =="A"]<-"001"
data2["genepop_y"][data2["genepop_y"] =="G"]<-"002"
data2["genepop_y"][data2["genepop_y"] =="C"]<-"003"
data2["genepop_y"][data2["genepop_y"] =="T"]<-"004"

#Concatenate columns genepop_x and genepop_y into column genepop_xy
data2$genepop_xy<- paste(data2$genepop_x, data2$genepop_y)
data2$genepop_xy<- gsub(" ", "", paste(data2$genepop_x, data2$genepop_y))

#Eliminate rows for which data$assay=SRY or ZFR
data2 <- data2[data2$assay != "ZFR", ]
data2 <- data2[data2$assay != "SRY", ]

#Eliminate "S60_c-ext_fore" "S72_ntc" "S84_ntc" "S96_ntc" 
data2 <- data2[data2$well != "S60_c-ext_fore", ]
data2 <- data2[data2$well != "C", ]
data2 <- data2[data2$well != "S84_ntc", ]
data2 <- data2[data2$well != "S96_ntc", ]
## we can check that this was successful by looking at the genepop$wells column as a factor. 
wells<-as.factor(data2$well)
levels(wells) #Is S84_ntc missing from the output? (yes)

# make a new data frame 98 col x 186 rows 
print(data2[row,column)
genepop<- as.data.frame(matrix(1:186,ncol=98))
 
#write the run name into genepop[1,1] <- c("22-06-2021-portugal)
genepop[1:186,] <- c("") 
genepop[1,1] <- c("22-06-2021-portugal") 


#Transpose assay into row 2
assay<- as.factor(data2$assay)
genepop[2,]<- t(data2$assay)
#write pop into genepop[3, 1]
genepop[3,1] <- c("Pop") 
genepop[4,1] <- c("") 

#Transpose S01 into genepop[4, 1]
genepop[4,1] <- c("S01_pipa") 
genepop[4,2] <- c(",") 
genepop[4,3:98]<- t(data2[data2$well == "S01_pipa",19])

genepop[5,1] <- c("Pop") 
genepop[6,1] <- c("S02_pulga") 
genepop[6,2] <- c(",") 
genepop[6,3:98]<- t(data2[data2$well == "S02_pulga",19])

genepop[7,1] <- c("Pop") 
genepop[8,1] <- c("S03_ramada") 
genepop[8,2] <- c(",") 
genepop[8,3:98]<- t(data2[data2$well == "S03_ramada",19])

genepop[9,1] <- c("Pop") 
genepop[10,1] <- c("S04_q1nairobi") 
genepop[10,2] <- c(",") 
genepop[10,3:98]<- t(data2[data2$well == "S04_q1nairobi",19])

genepop[11,1] <- c("Pop") 
genepop[12,1] <- c("S05_mel_2019") 
genepop[12,2] <- c(",") 
genepop[12,3:98]<- t(data2[data2$well == "S05_mel_2019",19])
### run from here
genepop[13,1] <- c("Pop") 
genepop[14,1] <- c("S06_qic27") 
genepop[14,2] <- c(",") 
genepop[14,3:98]<- t(data2[data2$well == "S06_qic27",19])

genepop[15,1] <- c("Pop") 
genepop[16,1] <- c("S07_0044ri") 
genepop[16,2] <- c(",") 
genepop[16,3:98]<- t(data2[data2$well == "S07_0044ri",19])

genepop[17,1] <- c("Pop") 
genepop[18,1] <- c("S08_1141gang") 
genepop[18,2] <- c(",") 
genepop[18,3:98]<- t(data2[data2$well == "S08_1141gang",19])
genepop[19,1] <- c("S20_1141gang") 
genepop[19,2] <- c(",") 
genepop[19,3:98]<- t(data2[data2$well == "S20_1141gang",19])
genepop[20,1] <- c("S32_1141gang") 
genepop[20,2] <- c(",") 
genepop[20,3:98]<- t(data2[data2$well == "S32_1141gang",19])
genepop[21,1] <- c("S44_1141gang") 
genepop[21,2] <- c(",") 
genepop[21,3:98]<- t(data2[data2$well == "S44_1141gang",19])

genepop[22,1] <- c("Pop") 
genepop[23,1] <- c("S09_quintagono") 
genepop[23,2] <- c(",") 
genepop[23,3:98]<- t(data2[data2$well == "S09_quintagono",19])
genepop[24,1] <- c("S21_quintagono") 
genepop[24,2] <- c(",") 
genepop[24,3:98]<- t(data2[data2$well == "S21_quintagono",19])
genepop[25,1] <- c("S33_quintagono") 
genepop[25,2] <- c(",") 
genepop[25,3:98]<- t(data2[data2$well == "S33_quintagono",19])
genepop[26,1] <- c("S45_quintagono") 
genepop[26,2] <- c(",") 
genepop[26,3:98]<- t(data2[data2$well == "S45_quintagono",19])

genepop[27,1] <- c("Pop") 
genepop[28,1] <- c("S10_hyp_r1pedra") 
genepop[28,2] <- c(",") 
genepop[28,3:98]<- t(data2[data2$well == "S10_hyp_r1pedra",19])
genepop[29,1] <- c("S22_hyp_r1pedra") 
genepop[29,2] <- c(",") 
genepop[29,3:98]<- t(data2[data2$well == "S22_hyp_r1pedra",19])
genepop[30,1] <- c("S22_hyp_r1pedra") 
genepop[30,2] <- c(",") 
genepop[30,3:98]<- t(data2[data2$well == "S34_r1pedra",19])
genepop[31,1] <- c("S46_hyp_r1pedra") 
genepop[31,2] <- c(",") 
genepop[31,3:98]<- t(data2[data2$well == "S46_hyp_r1pedra",19])

genepop[32,1] <- c("Pop") 
genepop[33,1] <- c("S11_m1_fresa") 
genepop[33,2] <- c(",") 
genepop[33,3:98]<- t(data2[data2$well == "S11_m1_fresa",19])
genepop[34,1] <- c("S23_m1_fresa") 
genepop[34,2] <- c(",") 
genepop[34,3:98]<- t(data2[data2$well == "S23_m1_fresa",19])
genepop[35,1] <- c("S35_m1_fresa") 
genepop[35,2] <- c(",") 
genepop[35,3:98]<- t(data2[data2$well == "S35_m1_fresa",19])
genepop[36,1] <- c("S47_m1_fresa") 
genepop[36,2] <- c(",") 
genepop[36,3:98]<- t(data2[data2$well == "S47_m1_fresa",19])

genepop[37,1] <- c("Pop") 
genepop[38,1] <- c("S12_hisopo_4") 
genepop[38,2] <- c(",") 
genepop[38,3:98]<- t(data2[data2$well == "S12_hisopo_4",19])
genepop[39,1] <- c("S24_hisopo_4") 
genepop[39,2] <- c(",") 
genepop[39,3:98]<- t(data2[data2$well == "S24_hisopo_4",19])
genepop[40,1] <- c("S36_hisopo_4") 
genepop[40,2] <- c(",") 
genepop[40,3:98]<- t(data2[data2$well == "S36_hisopo_4",19])
genepop[41,1] <- c("S48_hisopo_4") 
genepop[41,2] <- c(",") 
genepop[41,3:98]<- t(data2[data2$well == "S48_hisopo_4",19])

genepop[42,1] <- c("Pop") 
genepop[43,1] <- c("S13_pardal") 
genepop[43,2] <- c(",") 
genepop[43,3:98]<- t(data2[data2$well == "S13_pardal",19])

genepop[44,1] <- c("Pop") 
genepop[45,1] <- c("S14_mundo") 
genepop[45,2] <- c(",") 
genepop[45,3:98]<- t(data2[data2$well == "S14_mundo",19])

genepop[46,1] <- c("Pop") 
genepop[47,1] <- c("S15_paiciscaicus") 
genepop[47,2] <- c(",") 
genepop[47,3:98]<- t(data2[data2$well == "S15_paiciscaicus",19])

genepop[48,1] <- c("Pop") 
genepop[49,1] <- c("S16_quantana") 
genepop[49,2] <- c(",") 
genepop[49,3:98]<- t(data2[data2$well == "S16_quantana",19])

genepop[50,1] <- c("Pop") 
genepop[51,1] <- c("S17_mel_2020") 
genepop[51,2] <- c(",") 
genepop[51,3:98]<- t(data2[data2$well == "S17_mel_2020",19])

genepop[52,1] <- c("Pop") 
genepop[53,1] <- c("S18_q_infante_tapete") 
genepop[53,2] <- c(",") 
genepop[53,3:98]<- t(data2[data2$well == "S18_q_infante_tapete",19])

genepop[54,1] <- c("Pop") 
genepop[55,1] <- c("S19_0189mo") 
genepop[55,2] <- c(",") 
genepop[55,3:98]<- t(data2[data2$well == "S19_0189mo",19])

genepop[56,1] <- c("Pop") 
genepop[57,1] <- c("S25_pandora") 
genepop[57,2] <- c(",") 
genepop[57,3:98]<- t(data2[data2$well == "S25_pandora",19])

genepop[58,1] <- c("Pop") 
genepop[59,1] <- c("S26_quiribo") 
genepop[59,2] <- c(",") 
genepop[59,3:98]<- t(data2[data2$well == "S26_quiribo",19])
    
genepop[60,1] <- c("Pop") 
genepop[61,1] <- c("S27_nossa") 
genepop[61,2] <- c(",") 
genepop[61,3:98]<- t(data2[data2$well == "S27_nossa",19])

genepop[62,1] <- c("Pop") 
genepop[63,1] <- c("S28_qom") 
genepop[63,2] <- c(",") 
genepop[63,3:98]<- t(data2[data2$well == "S28_qom",19])

genepop[64,1] <- c("Pop") 
genepop[65,1] <- c("S29_quadrifolio") 
genepop[65,2] <- c(",") 
genepop[65,3:98]<- t(data2[data2$well == "S29_quadrifolio",19])

genepop[66,1] <- c("Pop") 
genepop[67,1] <- c("S30_q_gioes") 
genepop[67,2] <- c(",") 
genepop[67,3:98]<- t(data2[data2$well == "S30_q_gioes",19])

genepop[68,1] <- c("Pop") 
genepop[69,1] <- c("S31_0371ri") 
genepop[69,2] <- c(",") 
genepop[69,3:98]<- t(data2[data2$well == "S31_0371ri",19])

genepop[70,1] <- c("Pop") 
genepop[71,1] <- c("S37_parreira") 
genepop[71,2] <- c(",") 
genepop[71,3:98]<- t(data2[data2$well == "S37_parreira",19])

genepop[72,1] <- c("Pop") 
genepop[73,1] <- c("S38_quinquilharia") 
genepop[73,2] <- c(",") 
genepop[73,3:98]<- t(data2[data2$well == "S38_quinquilharia",19])

genepop[74,1] <- c("Pop") 
genepop[75,1] <- c("S39_rodion") 
genepop[75,2] <- c(",") 
genepop[75,3:98]<- t(data2[data2$well == "S39_rodion",19])

genepop[76,1] <- c("Pop") 
genepop[77,1] <- c("S40_r1lluvia") 
genepop[77,2] <- c(",") 
genepop[77,3:98]<- t(data2[data2$well == "S40_r1lluvia",19])

genepop[78,1] <- c("Pop") 
genepop[79,1] <- c("S41_nayem") 
genepop[79,2] <- c(",") 
genepop[79,3:98]<- t(data2[data2$well == "S41_nayem",19])

genepop[80,1] <- c("Pop") 
genepop[81,1] <- c("S42_nairobi") 
genepop[81,2] <- c(",") 
genepop[81,3:98]<- t(data2[data2$well == "S42_nairobi",19])
genepop[82,1] <- c("S85_nairobi") 
genepop[82,2] <- c(",") 
genepop[82,3:98]<- t(data2[data2$well == "S85_nairobi",19])

genepop[83,1] <- c("Pop") 
genepop[84,1] <- c("S43_0047ri") 
genepop[84,2] <- c(",") 
genepop[84,3:98]<- t(data2[data2$well == "S43_0047ri",19])

genepop[85,1] <- c("Pop") 
genepop[86,1] <- c("S49_nogado") 
genepop[86,2] <- c(",") 
genepop[86,3:98]<- t(data2[data2$well == "S49_nogado",19])
genepop[87,1] <- c("S78_nogado") 
genepop[87,2] <- c(",") 
genepop[87,3:98]<- t(data2[data2$well == "S78_nogado",19])

genepop[88,1] <- c("Pop") 
genepop[89,1] <- c("S50_quip") 
genepop[89,2] <- c(",") 
genepop[89,3:98]<- t(data2[data2$well == "S50_quip",19])

genepop[90,1] <- c("Pop") 
genepop[91,1] <- c("S51_ramalina") 
genepop[91,2] <- c(",") 
genepop[91,3:98]<- t(data2[data2$well == "S51_ramalina",19])

genepop[92,1] <- c("Pop") 
genepop[93,1] <- c("S52_moreira") 
genepop[93,2] <- c(",") 
genepop[93,3:98]<- t(data2[data2$well == "S52_moreira",19])

genepop[94,1] <- c("Pop") 
genepop[95,1] <- c("S53_oslo") 
genepop[95,2] <- c(",") 
genepop[95,3:98]<- t(data2[data2$well == "S53_oslo",19])

genepop[96,1] <- c("Pop") 
genepop[97,1] <- c("S54_p2neves") 
genepop[97,2] <- c(",") 
genepop[97,3:98]<- t(data2[data2$well == "S54_p2neves",19])

genepop[98,1] <- c("Pop") 
genepop[99,1] <- c("S55_0576gang") 
genepop[99,2] <- c(",") 
genepop[99,3:98]<- t(data2[data2$well == "S55_0576gang",19])

genepop[100,1] <- c("Pop") 
genepop[101,1] <- c("S56_pelos") 
genepop[101,2] <- c(",") 
genepop[101,3:98]<- t(data2[data2$well == "S56_pelos",19])
genepop[102,1] <- c("S68_pelos") 
genepop[102,2] <- c(",") 
genepop[102,3:98]<- t(data2[data2$well == "S68_pelos",19])
genepop[103,1] <- c("S80_pelos") 
genepop[103,2] <- c(",") 
genepop[103,3:98]<- t(data2[data2$well == "S80_pelos",19])
genepop[104,1] <- c("S92_pelos") 
genepop[104,2] <- c(",") 
genepop[104,3:98]<- t(data2[data2$well == "S92_pelos",19])
      
genepop[105,1] <- c("Pop") 
genepop[106,1] <- c("S57_picanco") 
genepop[106,2] <- c(",") 
genepop[106,3:98]<- t(data2[data2$well == "S57_picanco",19])
genepop[107,1] <- c("S69_picanco") 
genepop[107,2] <- c(",") 
genepop[107,3:98]<- t(data2[data2$well == "S69_picanco",19])
genepop[108,1] <- c("S81_picanco") 
genepop[108,2] <- c(",") 
genepop[108,3:98]<- t(data2[data2$well == "S81_picanco",19])
genepop[109,1] <- c("S93_picanco") 
genepop[109,2] <- c(",") 
genepop[109,3:98]<- t(data2[data2$well == "S93_picanco",19])

genepop[110,1] <- c("Pop") 
genepop[111,1] <- c("S58_oriana") 
genepop[111,2] <- c(",") 
genepop[111,3:98]<- t(data2[data2$well == "S58_oriana",19])
genepop[112,1] <- c("S70_oriana") 
genepop[112,2] <- c(",") 
genepop[112,3:98]<- t(data2[data2$well == "S70_oriana",19])
genepop[113,1] <- c("S82_oriana") 
genepop[113,2] <- c(",") 
genepop[113,3:98]<- t(data2[data2$well == "S82_oriana",19])
genepop[114,1] <- c("S94_oriana") 
genepop[114,2] <- c(",") 
genepop[114,3:98]<- t(data2[data2$well == "S94_oriana",19])

genepop[115,1] <- c("Pop") 
genepop[116, 1] <- c("S59_hisopo_3") 
genepop[116,2] <- c(",") 
genepop[116,3:98]<- t(data2[data2$well == "S59_hisopo_3",19])
genepop[117,1] <- c("S71_hisopo_3") 
genepop[117,2] <- c(",") 
genepop[117,3:98]<- t(data2[data2$well == "S71_hisopo_3",19])
genepop[118,1] <- c("S83_hisopo_3") 
genepop[118,2] <- c(",") 
genepop[118,3:98]<- t(data2[data2$well == "S83_hisopo_3",19])
genepop[119,1] <- c("S95_hisopo_3") 
genepop[119,2] <- c(",") 
genepop[119,3:98]<- t(data2[data2$well == "S95_hisopo_3",19])

genepop[120,1] <- c("Pop") 
genepop[121,1] <- c("S61_odeleite") 
genepop[121,2] <- c(",") 
genepop[121,3:98]<- t(data2[data2$well == "S61_odeleite",19])

genepop[122,1] <- c("Pop") 
genepop[123,1] <- c("S62_quadrado") 
genepop[123,2] <- c(",") 
genepop[123,3:98]<- t(data2[data2$well == "S62_quadrado",19])

genepop[124,1] <- c("Pop") 
genepop[125,1] <- c("S63_rombo") 
genepop[125,2] <- c(",") 
genepop[125,3:98]<- t(data2[data2$well == "S63_rombo",19])

genepop[126,1] <- c("Pop") 
genepop[127,1] <- c("S64_feto_nao_nascido") 
genepop[127,2] <- c(",") 
genepop[127,3:98]<- t(data2[data2$well == "S64_feto_nao_nascido",19])

genepop[128,1] <- c("Pop") 
genepop[129,1] <- c("S65_magreb") 
genepop[129,2] <- c(",") 
genepop[129,3:98]<- t(data2[data2$well == "S65_magreb",19])

genepop[130,1] <- c("Pop") 
genepop[131,1] <- c("S66_portela") 
genepop[131,2] <- c(",") 
genepop[131,3:98]<- t(data2[data2$well == "S66_portela",19])
genepop[132,1] <- c("S73_portela") 
genepop[132,2] <- c(",") 
genepop[132,3:98]<- t(data2[data2$well == "S73_portela",19])

genepop[133,1] <- c("Pop") 
genepop[134,1] <- c("S67_0706gang") 
genepop[134,2] <- c(",") 
genepop[134,3:98]<- t(data2[data2$well == "S67_0706gang",19])

genepop[135,1] <- c("Pop") 
genepop[136,1] <- c("S74_quimica") 
genepop[136,2] <- c(",") 
genepop[136,3:98]<- t(data2[data2$well == "S74_quimica",19])

genepop[137,1] <- c("Pop") 
genepop[138,1] <- c("S75_q1jacaranda") 
genepop[138,2] <- c(",") 
genepop[138,3:98]<- t(data2[data2$well == "S75_q1jacaranda",19])

genepop[139,1] <- c("Pop") 
genepop[140,1] <- c("S76_quilica") 
genepop[140,2] <- c(",") 
genepop[140,3:98]<- t(data2[data2$well == "S76_quilica",19])

genepop[141,1] <- c("Pop") 
genepop[142,1] <- c("S77_nabia") 
genepop[142,2] <- c(",") 
genepop[142,3:98]<- t(data2[data2$well == "S77_nabia",19])

genepop[143,1] <- c("Pop") 
genepop[144,1] <- c("S79_1738mo") 
genepop[144,2] <- c(",") 
genepop[144,3:98]<- t(data2[data2$well == "S79_1738mo",19])

genepop[145,1] <- c("Pop") 
genepop[146,1] <- c("S86_quilowat") 
genepop[146,2] <- c(",") 
genepop[146,3:98]<- t(data2[data2$well == "S86_quilowat",19])

genepop[147,1] <- c("Pop") 
genepop[148,1] <- c("S87_quimico") 
genepop[148,2] <- c(",") 
genepop[148,3:98]<- t(data2[data2$well == "S87_quimico",19])

genepop[149,1] <- c("Pop") 
genepop[150,1] <- c("S88_neves") 
genepop[150,2] <- c(",") 
genepop[150,3:98]<- t(data2[data2$well == "S88_neves",19])

genepop[151,1] <- c("Pop") 
genepop[152,1] <- c("S89_oliveira") 
genepop[152,2] <- c(",") 
genepop[152,3:98]<- t(data2[data2$well == "S89_oliveira",19])

genepop[153,1] <- c("Pop") 
genepop[154,1] <- c("S90_lluvia") 
genepop[154,2] <- c(",") 
genepop[154,3:98]<- t(data2[data2$well == "S90_lluvia",19])

genepop[155,1] <- c("Pop") 
genepop[156,1] <- c("S91_2258ri") 
genepop[156,2] <- c(",") 
genepop[156,3:98]<- t(data2[data2$well == "S91_2258ri",19])

### Export as *.prn
write.table(genepop, file ="/Volumes/GoogleDrive/My Drive/project_iberian_lynx/github_iberian_lynx/input_gimlet_22-06-2021-portugal.txt", row.names=F, col.names = F)

#Import *.txt as data to excel
#options: delimited, de-select ALL (no delimitation), select all as Text, manually remove NA, add "," to Row2

