---
title: "fluidigm_threshold1.5_july_2021"
author: "Tanya Lama"
date: "7/21/2021"
output: html_document
---

#Correcting allelic dropout from GIMLET consensus calls. 
We found that threshold 1 was too relaxed and threshold 2 was too strict and caused a lot of missing data. Therefore we retained threshold 1, and use this custom script to correct for homozygous calls where we don't have sufficient evidence to know whether or not they are actually just inflated allelic dropout. This script rescues (protects) the heterozygous calls from threshold 1, while being more conservative about homozygous calls.

by Tanya Lama.
Contact me at tanya.m.lama@gmail.com re: questions about this method

##final code
```{r}
#Load dependencies
library(readr)
library(dplyr)
library(methods)

#Set working directory
dir1 <- file.path("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/project_iberian_lynx_fluidigm/data_project_iberian_lynx_fluidigm/consensus_calls_threshold_1.5")
setwd(dir1)

#Load inputs
#R has a tendency to simplify 001001 to 1001, so we need to use colClasses to identify these items as non-numeric (see "factor")
input <- read.csv("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/project_iberian_lynx_fluidigm/scripts_project_iberian_lynx_fluidigm/input_consensus_for_threshold1.5_july-2021.csv", colClasses=rep("factor", 3))
inputraw<- input
#Run for each population
pop1<- input[1:5,]
input<- pop1
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop1<- input

##
pop2<- inputraw[6:10,]
input<- pop2
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop2<- input

##
pop3<- inputraw[11:15,]
input<- pop3
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop3<- input

##
pop4<- inputraw[16:20,]
input<- pop4
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop4<- input

##
pop5<- inputraw[21:25,]
input<- pop5
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop5<- input

##
pop6<- inputraw[26:30,]
input<- pop6
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop6<- input

##
pop7<- inputraw[31:35,]
input<- pop7
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop7<- input

##
pop8<- inputraw[36:40,]
input<- pop8
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop8<- input

##
pop9<- inputraw[41:45,]
input<- pop9
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop9<- input

##
pop10<- inputraw[46:50,]
input<- pop10
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop10<- input

##
pop11<- inputraw[51:55,]
input<- pop11
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop11<- input

##
pop12<- inputraw[56:60,]
input<- pop12
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop12<- input

##
pop13<- inputraw[61:65,]
input<- pop13
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop13<- input

##
pop14<- inputraw[66:70,]
input<- pop14
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop14<- input

##
pop15<- inputraw[71:75,]
input<- pop15
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop15<- input

##
pop16<- inputraw[76:80,]
input<- pop16
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop16<- input

##
pop17<- inputraw[81:85,]
input<- pop17
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop17<- input

##
pop18<- inputraw[86:90,]
input<- pop18
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop18<- input

##
pop19<- inputraw[91:95,]
input<- pop19
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop19<- input

##
pop20<- inputraw[96:100,]
input<- pop20
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop20<- input

##
pop21<- inputraw[101:105,]
input<- pop21
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop21<- input

##
pop22<- inputraw[106:110,]
input<- pop22
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop22<- input

##
pop23<- inputraw[111:115,]
input<- pop23
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop23<- input

##
pop24<- inputraw[116:120,]
input<- pop24
for (i in 3:ncol(input)) {
    if (input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"){
              input[6,i] <- print("000000")
              } else {
                input[6,i] <- print(input[5,i])  
              }
}

pop24<- input

#rbind all of the populations and their final (corrected) consensus calls together in one dataframe
masterpop<- rbind(pop1,pop2,pop3, pop4,pop5, pop6, pop7,pop8,pop9,pop10,pop11,pop12,pop13,pop14,pop15,pop16,pop17,pop18,pop19,pop20,pop21,pop22,pop23,pop24)
#write dataframe masterpop to *.txt
write.table(masterpop, file ="/Volumes/GoogleDrive/My Drive/project_iberian_lynx/project_iberian_lynx_fluidigm/data_project_iberian_lynx_fluidigm/consensus_calls_threshold_1.5/genepop_consensus_calls_threshold1.5_2021_raw.txt", row.names=F, col.names = T)

#Note that the nameless row after each population is the "allelic dropout-corrected" consensus for each population.
```


####Scratch. Do not delete
```
##Logic behind positions and combinations of positions for controlling allelic dropout
#fourth position is 00*00*
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000" && input[5,i]=="004004"|
#second position
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
#third position
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[1,i]=="000000" && input[2,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|
#first position
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="001001"|
input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="002002"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="003003"|                    input[2,i]=="000000" && input[3,i]=="000000" && input[4,i]=="000000" && input[5,i]=="004004"|

input %>% group_by(pop) %>% count("000000") %>%filter(n >=3)

for (i in 1:ncol(input)) {
    if input[,i]=="000000" && input[2,i]=="000000" && input[3,i]=="000000") {
     input[5,i] == c("bad_call")} 
else { input[5,i] <- input[5,i]   }
}

input[which(input[2:5,i] == "pop1" & input[,3]=="000000" & input[5,3]!="000000")]
which(input %>% count("000000") %>% filter(n >= 3))

count the true results from this expression:
nrow(input[input$X2071053=="000000",])

& input[,6]!="000000"
input$X2071053 %>% count("000000") %>% filter(n >= 3)
input %>% X2071053(input %>% count(StudentID) %>% filter(n > 3))

#Return df with a columns values that occur more than once [duplicate]
newd <- input %>% group_by(pop) %>% count("000000") %>%filter(n >=3)

input[which(input %>% count("000000") %>% filter(n >= 3))]

newd <-  input %>% group_by(X2071053) %>% filter(n()>3) #


for (i in input) {
if input[which(input[,2:6] %>% count("000000") %>% filter(n >= 3))] && input[5,i]!="000000") {
     input[7,i] == "bad_call"
   } else {
     input[7,i] <- input[6,i]   }
 }

cols<- which(input[,3:6] %>% count("000000") %>% filter(n >= 3))
which(input[,i] %>% count("000000") %>% filter(n >= 3))

#Import the SNP database in order to retrieve the SNP names from the scaffolds and positions. Note that David and Dani often used the positions as the SNP names. We have done the same here, although I think it makes interpretation rather difficult.
SNP_database <- read.csv2("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/project_iberian_lynx_fluidigm/data_project_iberian_lynx_fluidigm/snps_lista_suprema.csv")[,c(1,2,4)]
SNP_database
SNP_database$SCAFF_POSIT = paste(SNP_database$SCAFFOLD,SNP_database$POSITION,sep="_") 

#Retrieve SNP names when necessary, otherwise keep the original names (i.e. for the sex markers SRY and ZFR).
for each column, if
input_SNP_names <- vector('character')
for (i in colnames(input)) {
  if (startsWith(i,"lp23.")==F) {
    input_SNP_names <- c(input_SNP_names,i)
  } else {
    input_SNP_names <- c(input_SNP_names,unlist(SNP_database[which(SNP_database$SCAFF_POSIT==i),1],use.names=F))
  }
}
