---
title: "csv_to_genepop_format"
author: "Tanya Lama"
date: "6/29/2021"
output: html_document
---
csv_to_genepop_format
```{r setup, include=FALSE}
#Inputs 
library(readr)
library(dplyr)
library(stringr)

#Raw fluidigm data should be in *.csv format (see github for example)

#Set working directory
setwd("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/github_iberian_lynx/")
#Import *.csv
data<-  read.csv("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/data_iberian_lynx/data_david/output_fluidigm_david2.csv")

#Rename the columns
names(data) <- as.character(c("id", "assay", "allele_x", "allele_y", "name", "type", "auto", "confidence", "final", "converted", "fluoresc_x", "fluoresc_y", "comments"))
data<- data[16:9232,] #drop the first 13 rows. A fluidigm plate produces 9232 rows of raw data. If you are doing anything OTHER than taking raw fluidigm data in csv format --> genepop format, you will need to review all row and column selections in this script

#add a column called "well" to the FRONT of data
data<- data.frame(well = c(1:9217), data)

#extract the first half of id (S**_A**) and assign to well
data$well<- (str_extract(string = data$id, pattern = "S[0-96]+"))

#import *.csv with the proper id names
names<- read.csv("/Volumes/GoogleDrive/My Drive/project_iberian_lynx/R_iberian_lynx/input_names_csv_to_genepop_format.csv")

#for every well (S**) in data replace with well_id (S**_name) in names
#data["well"][data["well"] == "S96"] <- "S96_ntc" *** this works
data["well"][data["well"] =="S01"]<-"S01_27_1_2"
data["well"][data["well"] =="S02"]<-"S02_27_3_4"
data["well"][data["well"] =="S03"]<-"S03_28_3_3"
data["well"][data["well"] =="S04"]<-"S04_29_3_2"
data["well"][data["well"] =="S05"]<-"S05_30_2_4"
data["well"][data["well"] =="S06"]<-"S06_6_2"
data["well"][data["well"] =="S07"]<-"S07_22_1"
data["well"][data["well"] =="S08"]<-"S08_c1"
data["well"][data["well"] =="S09"]<-"S09_c4"
data["well"][data["well"] =="S10"]<-"S10_c9"
data["well"][data["well"] =="S11"]<-"S11_s20"
data["well"][data["well"] =="S12"]<-"S12_alicante_c13"
data["well"][data["well"] =="S13"]<-"S13_27_1_3"
data["well"][data["well"] =="S14"]<-"S14_28_1_2"
data["well"][data["well"] =="S15"]<-"S15_28_3_4"
data["well"][data["well"] =="S16"]<-"S16_29_3_3"
data["well"][data["well"] =="S17"]<-"S17_30_3_2"
data["well"][data["well"] =="S18"]<-"S18_6_2"
data["well"][data["well"] =="S19"]<-"S19_22_2"
data["well"][data["well"] =="S20"]<-"S20_c2"
data["well"][data["well"] =="S21"]<-"S21_c4"
data["well"][data["well"] =="S22"]<-"S22_c9"
data["well"][data["well"] =="S23"]<-"S23_alicante_c11"
data["well"][data["well"] =="S24"]<-"S24_alicante_c13"
data["well"][data["well"] =="S25"]<-"S25_27_1_4"
data["well"][data["well"] =="S26"]<-"S26_28_1_3"
data["well"][data["well"] =="S27"]<-"S27_29_1_2"
data["well"][data["well"] =="S28"]<-"S28_29_3_4"
data["well"][data["well"] =="S29"]<-"S29_30_3_3"
data["well"][data["well"] =="S30"]<-"S30_7_1"
data["well"][data["well"] =="S31"]<-"S31_22_2"
data["well"][data["well"] =="S32"]<-"S32_c2"
data["well"][data["well"] =="S33"]<-"S33_c5"
data["well"][data["well"] =="S34"]<-"S34_c9"
data["well"][data["well"] =="S35"]<-"S35_alicante_c11"
data["well"][data["well"] =="S36"]<-"S36_alicante_c14"
data["well"][data["well"] =="S37"]<-"S37_27_2_2"
data["well"][data["well"] =="S38"]<-"S38_28_1_4"
data["well"][data["well"] =="S39"]<-"S39_29_1_3"
data["well"][data["well"] =="S40"]<-"S40_30_1_2"
data["well"][data["well"] =="S41"]<-"S41_30_3_4"
data["well"][data["well"] =="S42"]<-"S42_7_2"
data["well"][data["well"] =="S43"]<-"S43_25_1"
data["well"][data["well"] =="S44"]<-"S44_c2"
data["well"][data["well"] =="S45"]<-"S45_c5"
data["well"][data["well"] =="S46"]<-"S46_m2"
data["well"][data["well"] =="S47"]<-"S47_alicante_c11"
data["well"][data["well"] =="S48"]<-"S48_alicante_c14"
data["well"][data["well"] =="S49"]<-"S49_27_2_3"
data["well"][data["well"] =="S50"]<-"S50_28_2_2"
data["well"][data["well"] =="S51"]<-"S51_29_1_4"
data["well"][data["well"] =="S52"]<-"S52_30_1_3"
data["well"][data["well"] =="S53"]<-"S53_4_1"
data["well"][data["well"] =="S54"]<-"S54_7_2"
data["well"][data["well"] =="S55"]<-"S55_25_2"
data["well"][data["well"] =="S56"]<-"S56_c3"
data["well"][data["well"] =="S57"]<-"S57_c5"
data["well"][data["well"] =="S58"]<-"S58_m2"
data["well"][data["well"] =="S59"]<-"S59_alicante_c12"
data["well"][data["well"] =="S60"]<-"S60_alicante_c14"
data["well"][data["well"] =="S61"]<-"S61_27_2_4"
data["well"][data["well"] =="S62"]<-"S62_28_2_3"
data["well"][data["well"] =="S63"]<-"S63_29_2_2"
data["well"][data["well"] =="S64"]<-"S64_30_1_4"
data["well"][data["well"] =="S65"]<-"S65_4_2"
data["well"][data["well"] =="S66"]<-"S66_21_1"
data["well"][data["well"] =="S67"]<-"S67_25_2"
data["well"][data["well"] =="S68"]<-"S68_c3"
data["well"][data["well"] =="S69"]<-"S69_c6"
data["well"][data["well"] =="S70"]<-"S70_m2"
data["well"][data["well"] =="S71"]<-"S71_alicante_c12"
data["well"][data["well"] =="S72"]<-"S72_ntc"
data["well"][data["well"] =="S73"]<-"S73_27_3_2"
data["well"][data["well"] =="S74"]<-"S74_28_2_4"
data["well"][data["well"] =="S75"]<-"S75_29_2_3"
data["well"][data["well"] =="S76"]<-"S76_30_2_2"
data["well"][data["well"] =="S77"]<-"S77_4_3"
data["well"][data["well"] =="S78"]<-"S78_21_2"
data["well"][data["well"] =="S79"]<-"S79_c1"
data["well"][data["well"] =="S80"]<-"S80_c3"
data["well"][data["well"] =="S81"]<-"S81_c6"
data["well"][data["well"] =="S82"]<-"S82_s20"
data["well"][data["well"] =="S83"]<-"S83_alicante_c12"
data["well"][data["well"] =="S84"]<-"S84_ntc"
data["well"][data["well"] =="S85"]<-"S85_27_3_3"
data["well"][data["well"] =="S86"]<-"S86_28_3_2"
data["well"][data["well"] =="S87"]<-"S87_29_2_4"
data["well"][data["well"] =="S88"]<-"S88_30_2_3"
data["well"][data["well"] =="S89"]<-"S89_6_1"
data["well"][data["well"] =="S90"]<-"S90_21_2"
data["well"][data["well"] =="S91"]<-"S91_c1"
data["well"][data["well"] =="S92"]<-"S92_c4"
data["well"][data["well"] =="S93"]<-"S93_c6"
data["well"][data["well"] =="S94"]<-"S94_s20"
data["well"][data["well"] =="S95"]<-"S95_alicante_c13"
data["well"][data["well"] =="S96"]<-"S96_ntc"

#assign the assay name (lp***) to just the numbers following _
data$assay<- as.character(data$assay) #must convert to characters first
data["assay"][data["assay"] =="lp23.s00014_2590354"]<-"2590354" 
data["assay"][data["assay"] =="lp23.s10433_1503895"]<-"1503895"
data["assay"][data["assay"] =="lp23.s20851_716372"]<-"716372"
data["assay"][data["assay"] =="lp23.s26104_908637"]<-"908637"
data["assay"][data["assay"] =="lp23.s31305_1737806"]<-"1737806"
data["assay"][data["assay"] =="lp23.s36488_4052964"]<-"4052964"
data["assay"][data["assay"] =="lp23.s00009_1834017"]<-"1834017"
data["assay"][data["assay"] =="lp23.s05280_563540"]<-"563540"
data["assay"][data["assay"] =="lp23.s10443_914709"]<-"914709"
data["assay"][data["assay"] =="lp23.s15671_1506609"]<-"1506609"
data["assay"][data["assay"] =="lp23.s20863_1655874"]<-"1655874"
data["assay"][data["assay"] =="lp23.s26096_1566241"]<-"1566241"
data["assay"][data["assay"] =="lp23.s00052_725687"]<-"725687"
data["assay"][data["assay"] =="lp23.s36542_710478"]<-"710478"
data["assay"][data["assay"] =="lp23.s20853_3066457"]<-"3066457"
data["assay"][data["assay"] =="lp23.s26145_507929"]<-"507929"
data["assay"][data["assay"] =="lp23.s31310_1086363"]<-"1086363"
data["assay"][data["assay"] =="lp23.s36495_3581524"]<-"3581524"
data["assay"][data["assay"] =="lp23.s00009_2846018"]<-"2846018"
data["assay"][data["assay"] =="lp23.s05325_381840"]<-"381840"
data["assay"][data["assay"] =="lp23.s10479_740770"]<-"740770"
data["assay"][data["assay"] =="lp23.s15684_800122"]<-"800122"
data["assay"][data["assay"] =="lp23.s20902_801628"]<-"801628"
data["assay"][data["assay"] =="lp23.s26116_753836"]<-"753836"
data["assay"][data["assay"] =="lp23.s00058_679888"]<-"679888"
data["assay"][data["assay"] =="lp23.s10475_739665"]<-"739665"
data["assay"][data["assay"] =="lp23.s20876_620249"]<-"620249"
data["assay"][data["assay"] =="lp23.s26165_396817"]<-"396817"
data["assay"][data["assay"] =="lp23.s31330_644231"]<-"644231"
data["assay"][data["assay"] =="lp23.s36500_2547318"]<-"2547318"
data["assay"][data["assay"] =="SRY"]<-"SRY"
data["assay"][data["assay"] =="lp23.s05352_266388"]<-"266388"
data["assay"][data["assay"] =="lp23.s10493_588415"]<-"588415"
data["assay"][data["assay"] =="lp23.s15686_741104"]<-"741104"
data["assay"][data["assay"] =="lp23.s20939_475959"]<-"475959"
data["assay"][data["assay"] =="lp23.s31280_3770256"]<-"3770256"
data["assay"][data["assay"] =="lp23.s00067_625966"]<-"625966"
data["assay"][data["assay"] =="lp23.s36582_514659"]<-"514659"
data["assay"][data["assay"] =="lp23.s20903_744497"]<-"744497"
data["assay"][data["assay"] =="lp23.s26166_401956"]<-"401956"
data["assay"][data["assay"] =="lp23.s31340_650544"]<-"650544"
data["assay"][data["assay"] =="lp23.s36504_2474946"]<-"2474946"
data["assay"][data["assay"] =="lp23.s00047_782246"]<-"782246"
data["assay"][data["assay"] =="lp23.s10425_4620618"]<-"4620618"
data["assay"][data["assay"] =="lp23.s10539_327149"]<-"327149"
data["assay"][data["assay"] =="lp23.s15697_710275"]<-"710275"
data["assay"][data["assay"] =="lp23.s20944_474858"]<-"474858"
data["assay"][data["assay"] =="lp23.s31291_2271462"]<-"2271462"
data["assay"][data["assay"] =="lp23.s00098_542097"]<-"542097"
data["assay"][data["assay"] =="lp23.s10491_591326"]<-"591326"
data["assay"][data["assay"] =="lp23.s20935_527144"]<-"527144"
data["assay"][data["assay"] =="lp23.s26186_334126"]<-"334126"
data["assay"][data["assay"] =="lp23.s31363_463230"]<-"463230"
data["assay"][data["assay"] =="lp23.s36537_860433"]<-"860433"
data["assay"][data["assay"] =="lp23.s00070_672876"]<-"672876"
data["assay"][data["assay"] =="lp23.s10427_1619116"]<-"1619116"
data["assay"][data["assay"] =="lp23.s15643_2579704"]<-"2579704"
data["assay"][data["assay"] =="lp23.s15710_553408"]<-"553408"
data["assay"][data["assay"] =="lp23.s20972_323729"]<-"323729"
data["assay"][data["assay"] =="lp23.s31294_1494647"]<-"1494647"
data["assay"][data["assay"] =="lp23.s00157_236533"]<-"236533"
data["assay"][data["assay"] =="lp23.s10513_455860"]<-"455860"
data["assay"][data["assay"] =="lp23.s20965_236982"]<-"236982"
data["assay"][data["assay"] =="lp23.s31279_1702572"]<-"1702572"
data["assay"][data["assay"] =="lp23.s36585_430428"]<-"430428"
data["assay"][data["assay"] =="lp23.s36540_772318"]<-"772318"
data["assay"][data["assay"] =="lp23.s05220_2270749"]<-"2270749"
data["assay"][data["assay"] =="lp23.s10427_2643321"]<-"2643321"
data["assay"][data["assay"] =="lp23.s15645_528326"]<-"528326"
data["assay"][data["assay"] =="lp23.s20851_1728823"]<-"1728823"
data["assay"][data["assay"] =="lp23.s26064_4484957"]<-"4484957"
data["assay"][data["assay"] =="lp23.s31295_1901450"]<-"1901450"
data["assay"][data["assay"] =="lp23.s05240_638843"]<-"638843"
data["assay"][data["assay"] =="lp23.s15639_4974369"]<-"4974369"
data["assay"][data["assay"] =="lp23.s26069_2728733"]<-"2728733"
data["assay"][data["assay"] =="lp23.s31284_643543"]<-"643543"
data["assay"][data["assay"] =="lp23.s31410_305622"]<-"305622"
data["assay"][data["assay"] =="lp23.s31390_349301"]<-"349301"
data["assay"][data["assay"] =="ZFR"]<-"ZFR"
data["assay"][data["assay"] =="lp23.s10438_2602837"]<-"2602837"
data["assay"][data["assay"] =="lp23.s15647_2259949"]<-"2259949"
data["assay"][data["assay"] =="lp23.s20857_507888"]<-"507888"
data["assay"][data["assay"] =="lp23.s26068_1522554"]<-"1522554"
data["assay"][data["assay"] =="lp23.s31338_714163"]<-"714163"
data["assay"][data["assay"] =="lp23.s10425_7686152"]<-"7686152"
data["assay"][data["assay"] =="lp23.s15650_667736"]<-"667736"
data["assay"][data["assay"] =="lp23.s26088_771095"]<-"771095"
data["assay"][data["assay"] =="lp23.s31296_2122346"]<-"2122346"
data["assay"][data["assay"] =="lp23.s31411_285842"]<-"285842"
data["assay"][data["assay"] =="lp23.s31401_367222"]<-"367222"
data["assay"][data["assay"] =="lp23.s05265_752266"]<-"752266"
data["assay"][data["assay"] =="lp23.s10441_815319"]<-"815319"
data["assay"][data["assay"] =="lp23.s15667_1617558"]<-"1617558"
data["assay"][data["assay"] =="lp23.s20860_1920172"]<-"1920172"
data["assay"][data["assay"] =="lp23.s26086_796406"]<-"796406"
data["assay"][data["assay"] =="lp23.s31351_557254"]<-"557254"

#data$converted has the final genotype calls (e.g., C:G). We need to convert these to three-digit genepop format (Invalid = 000, No Call = 000, A=001, G=002, C=003, T=004)

#Insert a column after data$converted
data<-data[, 1:14]
data<- data.frame(data, final_x = c(1:9217))
data<- data.frame(data, final_y = c(1:9217))
data<- data.frame(data, genepop_x = c(1:9217))
data<- data.frame(data, genepop_y = c(1:9217))
data<- data.frame(data, genepop_xy = c(1:9217))

#change Invalid to Invalid:Invalid and No Call to NoCall:NoCall
data$converted<- as.character(data$converted) #must convert to characters first
data["converted"][data["converted"] =="Invalid" ]<-"Invalid:Invalid"
data["converted"][data["converted"] =="No Call" ]<-"NoCall:NoCall"

#Split data$converted and assign to columns final_x and final_y
library(stringr)
converted_split<- str_split_fixed(data$converted, ":", 2)
converted_split<-as.data.frame(converted_split)
data$final_x <- converted_split$V1
data$final_y <- converted_split$V2

#Convert final_x and final_y into genepop three digit format in columns genepop_x and genepop_y
data$final_x<- as.character(data$final_x)
data$final_y<- as.character(data$final_y)
#copy values to genepop columns
data$genepop_x<- as.character(data$final_x)
data$genepop_y<- as.character(data$final_y)

####genepop_x
data["genepop_x"][data["genepop_x"] =="Invalid"]<-"000"
data["genepop_x"][data["genepop_x"] =="NoCall"]<-"000"
data["genepop_x"][data["genepop_x"] =="A"]<-"001"
data["genepop_x"][data["genepop_x"] =="G"]<-"002"
data["genepop_x"][data["genepop_x"] =="C"]<-"003"
data["genepop_x"][data["genepop_x"] =="T"]<-"004"

####genepop_y
data["genepop_y"][data["genepop_y"] =="Invalid"]<-"000"
data["genepop_y"][data["genepop_y"] =="NoCall"]<-"000"
data["genepop_y"][data["genepop_y"] =="A"]<-"001"
data["genepop_y"][data["genepop_y"] =="G"]<-"002"
data["genepop_y"][data["genepop_y"] =="C"]<-"003"
data["genepop_y"][data["genepop_y"] =="T"]<-"004"

#Concatenate columns genepop_x and genepop_y into column genepop_xy
data$genepop_xy<- paste(data$genepop_x, data$genepop_y)
data$genepop_xy<- gsub(" ", "", paste(data$genepop_x, data$genepop_y))

#Eliminate rows for which data$assay=SRY or ZFR
data <- data[data$assay != "ZFR", ]
data <- data[data$assay != "SRY", ]

#Eliminate "S60_c-ext_fore" "S72_ntc" "S84_ntc" "S96_ntc" 
#data2 <- data2[data2$well != "S60_c-ext_fore", ]
data <- data[data$well != "S72_ntc", ]
data <- data[data$well != "S84_ntc", ]
data <- data[data$well != "S96_ntc", ]
## we can check that this was successful by looking at the genepop$wells column as a factor. 
wells<-as.factor(data$well)
levels(wells) #Is S84_ntc missing from the output? (yes)

# make a new data frame 98 col x 186 rows 
#print(data[row,column])
genepop<- as.data.frame(matrix(1:186,ncol=98))
 
#write the run name into genepop[1,1] <- c("22-06-2021-portugal)
genepop[1:186,] <- c("") 
genepop[1,1] <- c("david") 
#data3<- data2$comments <- NULL 

#Transpose assay into row 2
assay<- as.factor(data$assay)
genepop[2,]<- t(data$assay)
#write pop into genepop[3, 1]
genepop[3,1] <- c("Pop") 
genepop[4,1] <- c("") 

data2<- data

#Transpose S01 into genepop[4, 1]
genepop[4,1] <- c("S01_27_1_2") 
genepop[4,2] <- c(",") 
genepop[4,3:97]<- t(data2[data2$well == "S01_27_1_2",19])
genepop[5,1] <- c("S13_27_1_3") 
genepop[5,2] <- c(",") 
genepop[5,3:97]<- t(data2[data2$well == "S13_27_1_3",19])
genepop[6,1] <- c("S25_27_1_4") 
genepop[6,2] <- c(",") 
genepop[6,3:97]<- t(data2[data2$well == "S25_27_1_4",19])

#pop
genepop[7,1] <- c("Pop") 
genepop[8,1] <- c("S37_27_2_2") 
genepop[8,2] <- c(",") 
genepop[8,3:97]<- t(data2[data2$well == "S37_27_2_2",19])
genepop[9,1] <- c("S49_27_2_3") 
genepop[9,2] <- c(",") 
genepop[9,3:97]<- t(data2[data2$well == "S49_27_2_3",19])
genepop[10,1] <- c("S61_27_2_4") 
genepop[10,2] <- c(",") 
genepop[10,3:97]<- t(data2[data2$well == "S61_27_2_4",19])

#pop
genepop[11,1] <- c("Pop") 
genepop[12,1] <- c("S73_27_3_2") 
genepop[12,2] <- c(",") 
genepop[12,3:97]<- t(data2[data2$well == "S73_27_3_2",19])
genepop[13,1] <- c("S85_27_3_3") 
genepop[13,2] <- c(",") 
genepop[13,3:97]<- t(data2[data2$well == "S85_27_3_3",19])
genepop[14,1] <- c("S02_27_3_4") 
genepop[14,2] <- c(",") 
genepop[14,3:97]<- t(data2[data2$well == "S02_27_3_4",19])

genepop[15,1] <- c("Pop") 
genepop[16,1] <- c("S14_28_1_2") 
genepop[16,2] <- c(",") 
genepop[16,3:97]<- t(data2[data2$well == "S14_28_1_2",19])
genepop[17,1] <- c("S26_28_1_3") 
genepop[17,2] <- c(",") 
genepop[17,3:97]<- t(data2[data2$well == "S26_28_1_3",19])
genepop[18,1] <- c("S38_28_1_4") 
genepop[18,2] <- c(",") 
genepop[18,3:97]<- t(data2[data2$well == "S38_28_1_4",19])

genepop[19,1] <- c("Pop") 
genepop[20,1] <- c("S50_28_2_2") 
genepop[20,2] <- c(",") 
genepop[20,3:97]<- t(data2[data2$well == "S50_28_2_2",19])
genepop[21,1] <- c("S62_28_2_3") 
genepop[21,2] <- c(",") 
genepop[21,3:97]<- t(data2[data2$well == "S62_28_2_3",19])
genepop[22,1] <- c("S74_28_2_4") 
genepop[22,2] <- c(",") 
genepop[22,3:97]<- t(data2[data2$well == "S74_28_2_4",19])

genepop[23,1] <- c("Pop") 
genepop[24,1] <- c("S86_28_3_2") 
genepop[24,2] <- c(",") 
genepop[24,3:97]<- t(data2[data2$well == "S86_28_3_2",19])
genepop[25,1] <- c("S03_28_3_3") 
genepop[25,2] <- c(",") 
genepop[25,3:97]<- t(data2[data2$well == "S03_28_3_3",19])
genepop[26,1] <- c("S15_28_3_4") 
genepop[26,2] <- c(",") 
genepop[26,3:97]<- t(data2[data2$well == "S15_28_3_4",19])

genepop[27,1] <- c("Pop") 
genepop[28,1] <- c("S27_29_1_2") 
genepop[28,2] <- c(",") 
genepop[28,3:97]<- t(data2[data2$well == "S27_29_1_2",19])
genepop[29,1] <- c("S39_29_1_3") 
genepop[29,2] <- c(",") 
genepop[29,3:97]<- t(data2[data2$well == "S39_29_1_3",19])
genepop[30,1] <- c("S51_29_1_4") 
genepop[30,2] <- c(",") 
genepop[30,3:97]<- t(data2[data2$well == "S51_29_1_4",19])

genepop[31,1] <- c("Pop") 
genepop[32,1] <- c("S63_29_2_2") 
genepop[32,2] <- c(",") 
genepop[32,3:97]<- t(data2[data2$well == "S63_29_2_2",19])
genepop[33,1] <- c("S75_29_2_3") 
genepop[33,2] <- c(",") 
genepop[33,3:97]<- t(data2[data2$well == "S75_29_2_3",19])
genepop[34,1] <- c("S87_29_2_4") 
genepop[34,2] <- c(",") 
genepop[34,3:97]<- t(data2[data2$well == "S87_29_2_4",19])

genepop[35,1] <- c("Pop") 
genepop[36,1] <- c("S04_29_3_2") 
genepop[36,2] <- c(",") 
genepop[36,3:97]<- t(data2[data2$well == "S04_29_3_2",19])
genepop[37,1] <- c("S16_29_3_3") 
genepop[37,2] <- c(",") 
genepop[37,3:97]<- t(data2[data2$well == "S16_29_3_3",19])
genepop[38,1] <- c("S28_29_3_4") 
genepop[38,2] <- c(",") 
genepop[38,3:97]<- t(data2[data2$well == "S28_29_3_4",19])

genepop[39,1] <- c("Pop") 
genepop[40,1] <- c("S40_30_1_2") 
genepop[40,2] <- c(",") 
genepop[40,3:97]<- t(data2[data2$well == "S40_30_1_2",19])
genepop[41,1] <- c("S52_30_1_3") 
genepop[41,2] <- c(",") 
genepop[41,3:97]<- t(data2[data2$well == "S52_30_1_3",19])
genepop[42,1] <- c("S64_30_1_4") 
genepop[42,2] <- c(",") 
genepop[42,3:97]<- t(data2[data2$well == "S64_30_1_4",19])

genepop[43,1] <- c("Pop") 
genepop[44,1] <- c("S76_30_2_2") 
genepop[44,2] <- c(",") 
genepop[44,3:97]<- t(data2[data2$well == "S76_30_2_2",19])
genepop[45,1] <- c("S88_30_2_3") 
genepop[45,2] <- c(",") 
genepop[45,3:97]<- t(data2[data2$well == "S88_30_2_3",19])
genepop[46,1] <- c("S05_30_2_4") 
genepop[46,2] <- c(",") 
genepop[46,3:97]<- t(data2[data2$well == "S05_30_2_4",19])

genepop[47,1] <- c("Pop") 
genepop[48,1] <- c("S17_30_3_2") 
genepop[48,2] <- c(",") 
genepop[48,3:97]<- t(data2[data2$well == "S17_30_3_2",19])
genepop[49,1] <- c("S29_30_3_3") 
genepop[49,2] <- c(",") 
genepop[49,3:97]<- t(data2[data2$well == "S29_30_3_3",19])
genepop[50,1] <- c("S41_30_3_4") 
genepop[50,2] <- c(",") 
genepop[50,3:97]<- t(data2[data2$well == "S41_30_3_4",19])
    
genepop[51,1] <- c("Pop") 
genepop[52,1] <- c("S53_4_1") 
genepop[52,2] <- c(",") 
genepop[52,3:97]<- t(data2[data2$well == "S53_4_1",19])
genepop[53,1] <- c("S65_4_2") 
genepop[53,2] <- c(",") 
genepop[53,3:97]<- t(data2[data2$well == "S65_4_2",19])
genepop[54,1] <- c("S77_4_3") 
genepop[54,2] <- c(",") 
genepop[54,3:97]<- t(data2[data2$well == "S77_4_3",19])

genepop[55,1] <- c("Pop") 
genepop[56,1] <- c("S89_6_1") 
genepop[56,2] <- c(",") 
genepop[56,3:97]<- t(data2[data2$well == "S89_6_1",19])
genepop[57,1] <- c("S06_6_2") 
genepop[57,2] <- c(",") 
genepop[57,3:97]<- t(data2[data2$well == "S06_6_2",19])
genepop[58,1] <- c("S18_6_2") 
genepop[58,2] <- c(",") 
genepop[58,3:97]<- t(data2[data2$well == "S18_6_2",19])

genepop[59,1] <- c("Pop") 
genepop[60,1] <- c("S30_7_1") 
genepop[60,2] <- c(",") 
genepop[60,3:97]<- t(data2[data2$well == "S30_7_1",19])
genepop[61,1] <- c("S42_7_2") 
genepop[61,2] <- c(",") 
genepop[61,3:97]<- t(data2[data2$well == "S42_7_2",19])
genepop[62,1] <- c("S54_7_2") 
genepop[62,2] <- c(",") 
genepop[62,3:97]<- t(data2[data2$well == "S54_7_2",19])

genepop[63,1] <- c("Pop") 
genepop[64,1] <- c("S66_21_1") 
genepop[64,2] <- c(",") 
genepop[64,3:97]<- t(data2[data2$well == "S66_21_1",19])
genepop[65,1] <- c("S78_21_2") 
genepop[65,2] <- c(",") 
genepop[65,3:97]<- t(data2[data2$well == "S78_21_2",19])
genepop[66,1] <- c("S90_21_2") 
genepop[66,2] <- c(",") 
genepop[66,3:97]<- t(data2[data2$well == "S90_21_2",19])

genepop[67,1] <- c("Pop") 
genepop[68,1] <- c("S07_22_1") 
genepop[68,2] <- c(",") 
genepop[68,3:97]<- t(data2[data2$well == "S07_22_1",19])
genepop[69,1] <- c("S19_22_2") 
genepop[69,2] <- c(",") 
genepop[69,3:97]<- t(data2[data2$well == "S19_22_2",19])
genepop[70,1] <- c("S31_22_2") 
genepop[70,2] <- c(",") 
genepop[70,3:97]<- t(data2[data2$well == "S31_22_2",19])

genepop[71,1] <- c("Pop") 
genepop[72,1] <- c("S43_25_1") 
genepop[72,2] <- c(",") 
genepop[72,3:97]<- t(data2[data2$well == "S43_25_1",19])
genepop[73,1] <- c("S67_25_2") 
genepop[73,2] <- c(",") 
genepop[73,3:97]<- t(data2[data2$well == "S67_25_2",19])
genepop[74,1] <- c("S55_25_2") 
genepop[74,2] <- c(",") 
genepop[74,3:97]<- t(data2[data2$well == "S55_25_2",19])

genepop[75,1] <- c("Pop") 
genepop[76,1] <- c("S08_c1") 
genepop[76,2] <- c(",") 
genepop[76,3:97]<- t(data2[data2$well == "S08_c1",19])
genepop[77,1] <- c("S79_c1") 
genepop[77,2] <- c(",") 
genepop[77,3:97]<- t(data2[data2$well == "S79_c1",19])
genepop[78,1] <- c("S91_c1") 
genepop[78,2] <- c(",") 
genepop[78,3:97]<- t(data2[data2$well == "S91_c1",19])

genepop[79,1] <- c("Pop") 
genepop[80,1] <- c("S32_c2") 
genepop[80,2] <- c(",") 
genepop[80,3:97]<- t(data2[data2$well == "S32_c2",19])
genepop[81,1] <- c("S44_c2") 
genepop[81,2] <- c(",") 
genepop[81,3:97]<- t(data2[data2$well == "S44_c2",19])
genepop[82,1] <- c("S20_c2") 
genepop[82,2] <- c(",") 
genepop[82,3:97]<- t(data2[data2$well == "S20_c2",19])

genepop[83,1] <- c("Pop") 
genepop[84,1] <- c("S56_c3") 
genepop[84,2] <- c(",") 
genepop[84,3:97]<- t(data2[data2$well == "S56_c3",19])
genepop[85,1] <- c("S68_c3") 
genepop[85,2] <- c(",") 
genepop[85,3:97]<- t(data2[data2$well == "S68_c3",19])
genepop[86,1] <- c("S80_c3") 
genepop[86,2] <- c(",") 
genepop[86,3:97]<- t(data2[data2$well == "S80_c3",19])

genepop[87,1] <- c("Pop") 
genepop[88,1] <- c("S21_c4") 
genepop[88,2] <- c(",") 
genepop[88,3:97]<- t(data2[data2$well == "S21_c4",19])
genepop[89,1] <- c("S09_c4") 
genepop[89,2] <- c(",") 
genepop[89,3:97]<- t(data2[data2$well == "S09_c4",19])
genepop[90,1] <- c("S92_c4") 
genepop[90,2] <- c(",") 
genepop[90,3:97]<- t(data2[data2$well == "S92_c4",19])

genepop[100,1] <- c("Pop") 
genepop[101,1] <- c("S33_c5") 
genepop[101,2] <- c(",") 
genepop[101,3:97]<- t(data2[data2$well == "S33_c5",19])
genepop[102,1] <- c("S45_c5") 
genepop[102,2] <- c(",") 
genepop[102,3:97]<- t(data2[data2$well == "S45_c5",19])
genepop[103,1] <- c("S57_c5") 
genepop[103,2] <- c(",") 
genepop[103,3:97]<- t(data2[data2$well == "S57_c5",19])

genepop[104,1] <- c("Pop") 
genepop[105, 1] <- c("S69_c6") 
genepop[105,2] <- c(",") 
genepop[105,3:97]<- t(data2[data2$well == "S69_c6",19])
genepop[106,1] <- c("S93_c6") 
genepop[106,2] <- c(",") 
genepop[106,3:97]<- t(data2[data2$well == "S93_c6",19])
genepop[107,1] <- c("S81_c6") 
genepop[107,2] <- c(",") 
genepop[107,3:97]<- t(data2[data2$well == "S81_c6",19])

genepop[108,1] <- c("Pop") 
genepop[109,1] <- c("S34_c9") 
genepop[109,2] <- c(",") 
genepop[109,3:97]<- t(data2[data2$well == "S34_c9",19])
genepop[110,1] <- c("S22_c9") 
genepop[110,2] <- c(",") 
genepop[110,3:97]<- t(data2[data2$well == "S22_c9",19])
genepop[111,1] <- c("S10_c9") 
genepop[111,2] <- c(",") 
genepop[111,3:97]<- t(data2[data2$well == "S10_c9",19])

genepop[112,1] <- c("Pop") 
genepop[113,1] <- c("S46_m2") 
genepop[113,2] <- c(",") 
genepop[113,3:97]<- t(data2[data2$well == "S46_m2",19])
genepop[114,1] <- c("S58_m2") 
genepop[114,2] <- c(",") 
genepop[114,3:97]<- t(data2[data2$well == "S58_m2",19])
genepop[115,1] <- c("S70_m2") 
genepop[115,2] <- c(",") 
genepop[115,3:97]<- t(data2[data2$well == "S70_m2",19])

genepop[116,1] <- c("Pop") 
genepop[117,1] <- c("S82_s20") 
genepop[117,2] <- c(",") 
genepop[117,3:97]<- t(data2[data2$well == "S82_s20",19])
genepop[118,1] <- c("S94_s20") 
genepop[118,2] <- c(",") 
genepop[118,3:97]<- t(data2[data2$well == "S94_s20",19])
genepop[119,1] <- c("S11_s20") 
genepop[119,2] <- c(",") 
genepop[119,3:97]<- t(data2[data2$well == "S11_s20",19])

genepop[120,1] <- c("Pop") 
genepop[121,1] <- c("S35_alicante_c11") 
genepop[121,2] <- c(",") 
genepop[121,3:97]<- t(data2[data2$well == "S35_alicante_c11",19])
genepop[122,1] <- c("S47_alicante_c11") 
genepop[122,2] <- c(",") 
genepop[122,3:97]<- t(data2[data2$well == "S47_alicante_c11",19])
genepop[123,1] <- c("S23_alicante_c11") 
genepop[123,2] <- c(",") 
genepop[123,3:97]<- t(data2[data2$well == "S23_alicante_c11",19])

genepop[124,1] <- c("Pop") 
genepop[125,1] <- c("S59_alicante_c12") 
genepop[125,2] <- c(",") 
genepop[125,3:97]<- t(data2[data2$well == "S59_alicante_c12",19])
genepop[126,1] <- c("S71_alicante_c12") 
genepop[126,2] <- c(",") 
genepop[126,3:97]<- t(data2[data2$well == "S71_alicante_c12",19])
genepop[127,1] <- c("S83_alicante_c12") 
genepop[127,2] <- c(",") 
genepop[127,3:97]<- t(data2[data2$well == "S83_alicante_c12",19])

genepop[128,1] <- c("Pop") 
genepop[129,1] <- c("S12_alicante_c13") 
genepop[129,2] <- c(",") 
genepop[128,3:97]<- t(data2[data2$well == "S12_alicante_c13",19])
genepop[130,1] <- c("S95_alicante_c13") 
genepop[130,2] <- c(",") 
genepop[130,3:97]<- t(data2[data2$well == "S95_alicante_c13",19])
genepop[131,1] <- c("S24_alicante_c13") 
genepop[131,2] <- c(",") 
genepop[131,3:97]<- t(data2[data2$well == "S24_alicante_c13",19])

genepop[132,1] <- c("Pop") 
genepop[133,1] <- c("S36_alicante_c14") 
genepop[133,2] <- c(",") 
genepop[133,3:97]<- t(data2[data2$well == "S36_alicante_c14",19])
genepop[134,1] <- c("S48_alicante_c14") 
genepop[134,2] <- c(",") 
genepop[134,3:97]<- t(data2[data2$well == "S48_alicante_c14",19])
genepop[135,1] <- c("S60_alicante_c14") 
genepop[135,2] <- c(",") 
genepop[135,3:97]<- t(data2[data2$well == "S60_alicante_c14",19])

genepop[136,1] <- c("Pop") 
genepop[137,1] <- c("S72_ntc") 
genepop[137,2] <- c(",") 
genepop[137,3:97]<- t(data2[data2$well == "S72_ntc",19])
genepop[138,1] <- c("S84_ntc") 
genepop[138,2] <- c(",") 
genepop[138,3:97]<- t(data2[data2$well == "S84_ntc",19])
genepop[139,1] <- c("S96_ntc") 
genepop[139,2] <- c(",") 
genepop[139,3:97]<- t(data2[data2$well == "S96_ntc",19])

### Export as *.prn
write.table(genepop, file ="/Volumes/GoogleDrive/My Drive/project_iberian_lynx/github_iberian_lynx/input_gimlet_david-16-07-21.txt", row.names=F, col.names = F)

#Import *.txt as data to excel
#options: delimited, de-select ALL (no delimitation), select all as Text, manually remove NA, add "," to Row2

